version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo "Building the App"
      - mvn install -DskipTests=true
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - target/shoeServerApp.jar
  discard-paths: true